package model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Information implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.String address;
	private java.lang.String city;

	public Information() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public Information(java.lang.String name, java.lang.String address,
			java.lang.String city) {
		this.name = name;
		this.address = address;
		this.city = city;
	}

}